### PR TITLE
Component page: [Content item horizontal] Add info, image, & variations

### PR DESCRIPTION
**Pull request by shixiedesign**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1032

### Changelog

**New**

- Added "Variations" section with info & image on "Content item horizontal - with media" and "Content item horizontal - with thumbnail"

**Changed**

- Added info & image for "Content item horizontal - defaultt"

### CODE REVIEW

**Comment by shixiedesign** [comment]
Hi @janchild this PR adds images and some usage details to Content item horizontal: 
https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1092/components/content-item-horizontal

**Review by janchild — COMMENTED** [review]
@shixiedesign I made some very minor tweaks! Let me know if you're okay with these.

**Comment by shixiedesign** [comment]
Looks great! Thanks @janchild 👍

**Review by janchild — APPROVED** [review]
👍 🥂

**Pull request merged**
