### PR TITLE
chore(pages): hide various components/sections

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

Closes https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1724

### Description

Temporarily hide certain components and sections

### Changelog

**New**

- {{new thing}}

**Changed**

- various components removed/hidden in left nav Components section
- Patterns section hidden in left nav

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by ariellalgilmore — COMMENTED** [review]
Looks good! I think you also have to update the components.json file so it doesn't appear in the overview/gallery: https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1722/components/overview

**Comment by kennylam** [comment]
I think the original ask from @oliviaflory was to remove the component guidance pages until the v2 versions were ready, not to remove them from the website entirely?

**Comment by oliviaflory** [comment]
>I think the original ask from @oliviaflory was to remove the component guidance pages until the v2 versions were ready, not to remove them from the website entirely?

Great question/point @kennylam I think it depends on the component, per Ari's point we wouldn't want any deprecated components showing up in the Component gallery page like they are now. I'll get a list together of what should be permanently deleted vs just hidden until we can complete the docs for the v2 site so we can make sure everything is clear.

**Comment by oliviaflory** [comment]
### Components 

| Component | Action |
| --- | --- | 
| Back to top | – |
| Callout quote | – |
| Callout with media | – |
| Cards | – |
| Card group | – |
| Card section | **Delete** |
| Card section carousel  | **Delete** |
| Carousel | – |
| Content block | – |
| Content block cards | **Delete** |
| Content block horizontal | **Delete** |
| Content block media | **Delete** |
| Content block mixed | **Delete** |
| Content block segmented | **Delete** |
| Content group | Keep |
| Content group cards | **Delete** |
| Content group pictograms | **Delete** |
| Content group simple | **Delete** |
| Content item | – |
| Content item row (prev horizontal) | – |
| Content section | – |
| CTA block & section | – |
| Dotcom shell | – |
| Expressive modal | – |
| Feature section | – |
| Filter panel | – |
| Footer | – |
| Horizontal rule | – |
| Images | – |
| Language selector | **Delete** |
| Layout | – |
| Lead space | – |
| Lead space block | – |
| Lead space search | – |
| Leaving IBM modal | – |
| Light box media viewer | – |
| Link list | – |
| Link list section | – Bring back?? |
| Link with icon | – |
| Locale modal | – |
| Logo grid | _Hide_ Is AEM taking this on? |
| Masthead | – |
| Pictogram item | **Delete** |
| Quote | – |
| Table of contents | – |
| Tabs extended | – |
| Tags | **Delete** we ended up deprecating in favor of using Carbon tags directly |
| ~Universal banner~ Global banner | – |
| Video | – |

**Comment by kennylam** [comment]
Thanks @oliviaflory, made the additional updates.

**Review by oliviaflory — APPROVED** [review]
LGTM!

**Pull request merged**
