### PR TITLE
[Masthead] Add reason why masthead must stay white

### PR DESCRIPTION
**Pull request by shixiedesign**
### Related Ticket(s)

#1015

### Description
- Added masthead page, `Options > White theme only` section

### CODE REVIEW

**Review by JBrandwine — CHANGES_REQUESTED** [review]
@shixiedesign, I reorganized some of the third paragraph and otherwise made a few minor changes for grammar. See below...

As a mandatory component of the IBM.com web experience, the white masthead should remain consistent, creating a branded anchor across all pages.

Visually the white theme has proven to be safer and more versatile than the dark masthead, which could create a stark band when used in contrast, or blend into a dark lead space. Keeping the global navigation locked, above and "out of the way" allows page makers to explore any theming combinations for the rest of the page.

Unlike some products and dashboards, the IBM.com web experience does not support dark and light mode switching. The majority of IBM.com are marketing pages using expressive imagery, company logos, and different themes across page sections. Dark and light mode switching can cause unexpected results at scale, which is another reason for keeping the masthead white.

**Comment by JBrandwine** [comment]
Forgot to add the last note but it is good as is...

**Note:** If you believe a color theme change will have a positive impact on your web experience, please contact us and we will evaluate it together.

**Comment by shixiedesign** [comment]
Ready for another review @JBrandwine !

**Review by JBrandwine — CHANGES_REQUESTED** [review]
@shixiedesign 

Apologies, one more correction after rereading the last paragraph.

Unlike some products and dashboards, the IBM.com web experience does not support dark and light mode switching. The majority of IBM.com is comprised of marketing pages using expressive imagery, company logos, and different themes across page sections. Dark and light mode switching can cause unexpected results at scale, which is another reason for keeping the masthead white.

**Review by JBrandwine — APPROVED** [review]
@shixiedesign this looks good to me!

**Pull request merged**
