### PR TITLE
Update masthead

### LINKED ISSUE #731: Update the Masthead component page - Target sprint 20-24
**User story**
As a DDS designer I need to update the Masthead component page to reflect the updates made to the Masthead L0 and L1.

The current masthead component documentation is slightly different from the MVP content template. I believe this unique content order and sections were created to address the complexity of the masthead.

**Tasks** 
- [x] Review the current content sections and determine if they need to be updated

- [x] Update the content to reflect all L1 changes
- [x] Update the images of the L1 to reflect all changes
- [x] Update behavior section to include overflow feature 
- [x] Share with Jenny and Wonil for approval

**Acceptance criteria**
- [ ] Content drafted and approved by Wonil and Jenny
- [ ] Content and design updated with markdowns.

### PR DESCRIPTION
**Pull request by oliviaflory**
Updates all images for the masthead L0 and L1
Updates the content and content order for masthead
Adds documentation of overflow feature
Deletes old masthead images from the repo

### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

Closes #731 

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by oliviaflory** [comment]
@JennySanchez @wonilsuhibm FYI there’s two tests happening on this page:
1. Should we display the masthead on its own, or with padding above and below like all other components? You can see this in the default masthead and search open by default examples
Screen Shot 2020-11-16 at 5 30 32 PM

2. Search open by default section is testing the [image size recommended](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Production-guidelines) by Carbon of 736px wide and exported as a transparent PNG. Not sure it’s ideal, maybe I interpreted the sizes wrong in the guidelines too because it looks fuzzy to me. 
Screen Shot 2020-11-16 at 5 30 50 PM

Still looking for overall content flow feedback that I can address Wednesday when I'm back!

**Comment by JennySanchez** [comment]
@oliviaflory 

For the image, I think to display the masthead on its works better for me (see below). The extra white background on the top and bottom looks off to me but it will only work if the top and bottom white spaces are NOT part of the masthead set up.

Screen Shot 2020-11-17 at 1 31 06 PM


I am also not sure if the Anatomy image is working. Is there any way we can add white space around the component "itself"? Like the [UI shell header](https://www.carbondesignsystem.com/components/UI-shell-header/usage) example from Carbon below.

header_anatomy


For the image size, I know you test out the Carbon set up, but did you try the set up in the MVP template? If you did, are there any differences?

About the fuzzy image, from my learning, image fuzziness has nothing to do with the sizes of the file format as tested before. This is caused by the 2x image export for retina display so, in the browser, it looks fuzzy. 

A few small edits and findings to share with you.

- Masthead Level 1/Anatomy/Search: The search icon is persistent... (Needs "." after IBM.com)
- Masthead Level 1/Anatomy/Profile: Links to a `users` MyIBM profile... (a `user's` MyIBM profile?)
- Design and functional specifications/ Masthead can be viewed here...(Needs "." after here)
- "All nav labels will collapse..." - Instead of "nav", I think we should use "navigation" across all content on the page where "nav" is currently used. What do you think?

Let me know if my comments make sense and if you have any questions.

**Comment by oliviaflory** [comment]
@JennySanchez thanks for all the feedback, I will make the updates you suggested. 

I'm not sure what you meant by this comment though:
> For the image size, I know you test out the Carbon set up, but did you try the set up in the MVP template? If you did, are there any differences?

It's possible I don't fully understand their guidelines too, maybe we could chat?

**Comment by oliviaflory** [comment]
This PR should be ready for review now @JennySanchez @wonilsuhibm

**Review by JennySanchez — APPROVED** [review]
I do not have additional edits and the page looks good to me. Thank you, Olivia.

**Comment by oliviaflory** [comment]
@wonilsuhibm when you can, need your review and possible approval 🙏

**Comment by wonilsuhibm** [comment]
@oliviaflory thank you. Overall this page look great. Some not-high-priority comments, maybe for the next iteration?

- Not a high priority, once again, but I always felt this sentent, "L is abbreviated for the “Level” starting at base 0, the Level refers to the hierarchy of the navigation on the page." was a bit awkward in the current placement, part of that high level intro. Maybe pull it out as a footnote below the intro text or something? Just a thought.

- When to use: should this be a bit more open—currently it almost feels like it's usage is limited to those two pages.

- Can the **Responsive** and **Mobile** sections be merged, since they are talking about the same or very related topics?

That's about it. Thank you!

**Comment by oliviaflory** [comment]
@wonilsuhibm addressed your comments if you could take a look at the new deploy preview

**Comment by wonilsuhibm** [comment]
Looks great. Thank you @oliviaflory

**Comment by JennySanchez** [comment]
Good job, Olivia!!! <3

**Pull request merged**
