### PR TITLE
feat/docs--content-group

### LINKED ISSUE #1633: [Website] Content group
The Content group page needs updates for v2

**v2 guidance updates:**
- [ ] Replace references to `content block` with `content section`.
- [ ] Remove `Content. block` from component description in JSON
- [ ] In Related components section, remove all but `card group`
- [ ] Consider a notification at the top indicating that multiple `content group-x` components were deprecated, but `content group` can be modified to achieve any of those.
- [ ] Use lower case for component names.

**v2 media updates:**
- [ ] Replace Overview image for new `card link` design
- [ ] Replace animated example GIF (this might take some time to re-do)

### PR DESCRIPTION
**Pull request by oliviaflory**
### Related Ticket(s)

Closes #1633 

### Description

Updates the Content group page for v2 MVP

### Changelog

**New**

- images

**Changed**

- MDX guidance
- Swapped Related components with content block / content section / content item (@RichKummer LMK what you think of this as an idea for all content X components)
- TBD json file (I'm scared to update that)
- Last sentence in Tips and techniques is weird.. need to review with @RichKummer to get his opinion of what the heck that sentence could mean?

**Removed**

- Related components

### CODE REVIEW

**Review by RichKummer — COMMENTED** [review]
* I like the added related components table, I think it helps pull those together – I'll add this for `content item`!
* It looks like the json file needs to change for the description up top to come through, I'll add a commit for this!

**Comment by RichKummer** [comment]
I also just added a commit for the tips and techniques section @oliviaflory to try and clean that up. Let me know if that makes it cleaner!

**Comment by oliviaflory** [comment]
@RichKummer Does this one seem OK to merge then? Or does the json file still need an update?

**Review by kennylam — APPROVED** [review]
LGTM!

**Pull request merged**
