### PR TITLE
Cards page overview image update

### PR DESCRIPTION
**Pull request by shixiedesign**
### Related Ticket(s)

Based on template created in #1216, I created a new preview image for Cards page.

image

### CODE REVIEW

**Comment by janchild** [comment]
@shixiedesign Not sure what's happening here but the deploy preview is showing the old image.

**Comment by janchild** [comment]
@shixiedesign One thing to fix here is the label for `Card link`. It's currently saying `Card in card`. ;)

**Review by janchild — APPROVED** [review]
⚡

**Review by RichKummer — APPROVED** [review]
Updates look great!

**Pull request merged**
