### PR TITLE
Adding Lead space search page

### PR DESCRIPTION
**Pull request by DragosRistici**
### Related Ticket(s)
Issue #993

### Description

Adding the Lead space search component page to the website.

### CODE REVIEW

**Comment by shixiedesign** [comment]
Hey @DragosRistici  you might have forgotten to add the `Lead space search` to the navigation data file? Not seeing the page in left nav.

**Comment by DragosRistici** [comment]
> Hey @DragosRistici you might have forgotten to add the `Lead space search` to the navigation data file? Not seeing the page in left nav.

Yep. Thank you. Doing it asap.

**Comment by DragosRistici** [comment]
Done: 
1. Creating the file
2. Adding the images folder and the images
3. Creating and adding the lead_space_search.svg to the ComponentGallery/images folder
4. Adding the page to the nav-items.yaml file
5. Adding the comp status
6. Adding the Development Documentation details

**Review by janchild — COMMENTED** [review]
@DragosRistici I made some edits to the mdx and have one suggestion here too. 🚀 

Awesome work!

**Review by janchild — APPROVED** [review]
@DragosRistici I know you're going to create an animation of the scrolling behavior, but from a content perspective this is ready to go! 🚀

**Review by shixiedesign — APPROVED** [review]
Wow! This is a high bar to achieve. I hope our devs do get the component build as expected. This looks fantastic. Let's hold to merge until the component is QA'ed and merged to production. But this looks great! So good to see the animation!

**Comment by shixiedesign** [comment]
Gonna say let’s merge this PR if you all are ok with messiness. We can add a notification “coming soon” after this PR merges. Thoughts? @janchild @DragosRistici

**Comment by DragosRistici** [comment]
> Gonna say let’s merge this PR if you all are ok with messiness. We can add a notification “coming soon” after this PR merges. Thoughts? @janchild @DragosRistici

If we do that, we have to add the "coming soon" very soon. @shixiedesign

**Comment by janchild** [comment]
> Gonna say let’s merge this PR if you all are ok with messiness. We can add a notification “coming soon” after this PR merges. Thoughts? @janchild @DragosRistici

Where is the messiness? This looks great to me! 👯

**Comment by janchild** [comment]
@DragosRistici @shixiedesign Do we want to change the `Variations` headings to `Options` while we're here?

**Comment by shixiedesign** [comment]
Sure! And Overview instead of Default? And I've created an issue for adding "coming soon" message. #1111

**Comment by DragosRistici** [comment]
Sure. Variations to Options and Overview instead of Default. Coming up.

**Pull request merged**
