### PR TITLE
feat(back-to-top): v2 updates

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
[1587](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1587)

### Description
This is a small update to back to top documentation with a brief demo GIF and wording additions.

### Changelog

**New**

- component usage explanations

**Changed**

- small wording changes

**Removed**

- old use cases pictures

### CODE REVIEW

**Comment by oliviaflory** [comment]
@IgnacioBecerra This looks awesome with the GIF!

Two small comments:

- [ ] We're adjusting the component template order of the anchor links and moving the Resources cards above the Content guidance. Could you update the anchor links order and move the resource link widget thing
Screenshot 2023-11-08 at 4 02 29 PM


- [ ] the old use case images are still appearing in the deploy preview and I don't see them deleted in the files changed? maybe a missed commit? I agree we can delete them!

**Comment by IgnacioBecerra** [comment]
@oliviaflory addressed your comments! @RichKummer sent over two images to replace the old ones, should be updated now!

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Review by RichKummer — COMMENTED** [review]
@IgnacioBecerra just sent a better image for the second one for the `Use case` section. Just two more things beyond that:
- [x] The resource cards are still appearing in the wrong spot. They should be just above `Content guidance` in the content:

Screenshot 2023-11-10 at 3 55 35 PM

- [x] Could you add captions for the two images under `Use case`? I think they could use a little extra context:

For `back-to-top-overview-01`: "As the user scrolls, back to top remains visible at the bottom of the window"

For `back-to-top-overview-02`: "Once the footer is in view, back to top will stay above the footer"

**Comment by IgnacioBecerra** [comment]
@RichKummer should be good now!

**Review by oliviaflory — APPROVED** [review]
LGTM, thanks @IgnacioBecerra !

**Comment by oliviaflory** [comment]
@IgnacioBecerra here is the GIF player for Gatsby https://gatsby.carbondesignsystem.com/components/GifPlayer

We'll want to use the 'dark' prop, do you think you can pull a static frame from your GIF or one that sort of matches?

**Pull request merged**
