### PR TITLE
fix(links): update storybook react links

### PR DESCRIPTION
**Pull request by kennylam**
### Description

Fixes links to Storybook React component examples

### Changelog

**Changed**

- update links for Storybook React

### CODE REVIEW

**Review by shixiedesign — APPROVED** [review]
TY!

**Comment by shixiedesign** [comment]
oops @kennylam the last commit failed to build. Do you know how to fix?

**Comment by oliviaflory** [comment]
Didn't get a chance to comment yet, but both WC and React links to Leadspace are broken.

Was going to try to check the others

**Comment by shixiedesign** [comment]
Oh **Lead space web component** one is broken. Sorry!

**Comment by shixiedesign** [comment]
Taking another look at this PR, realized the goal was to update React links. There are still some web comp links not working, but we will address in separate PR. Thanks @kennylam !

**Review by shixiedesign — APPROVED** [review]

**Pull request merged**
