### PR TITLE
fix(prettier): prevent proseWrap

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#1339

### Description

This PR updates the prettier config so that inline JSX links won't conflict with MDX formatting. It also fixes several instances of this breakage and runs `prettier` across the codebase

when reviewing it would probably be best to check the "Hide whitespace" option and apply

image

### Changelog

**Changed**

- prose wrap prettier config option
- resolve broken formatting for inline links in MDX
- format codebase

**Removed**

- deprecated JSX bracket same line prettier config option

### CODE REVIEW

**Review by janchild — APPROVED** [review]
🙏 🙏 🙏

**Comment by janchild** [comment]
@emyarod Thank you! This has fixed the link wrap in the Aside components on each of the three pages of the `Designing` section. I still see an issue on the [Sketch kit page here](https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1341/designing/sketch-kit#sketch-tutorials). Do I need to do anything on my side? thanks!

**Comment by emyarod** [comment]
@janchild it should be resolved now, I just updated the PR to include that page since it looks like it was added after this PR was created

**Comment by janchild** [comment]
> @janchild it should be resolved now, I just updated the PR to include that page since it looks like it was added after this PR was created

Thank you, @emyarod!

**Pull request merged**
