### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by ljcarot**
### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by ljcarot** [comment]
@JennySanchez Can you review when you get a chance?  I removed reference to Drupa v2

**Comment by JennySanchez** [comment]
Hi @ljcarot, The "Afterburner" and "Marketing Platforms Drupal CMS website." links when I clicked on them they are not linked.

Screen Shot 2020-12-07 at 6 51 17 PM
Screen Shot 2020-12-07 at 6 50 13 PM

**Comment by ljcarot** [comment]
I didn't change anything related to the second link.  Can you check again.  They are working for me

**Comment by JennySanchez** [comment]
Both links work for me now. Thank you, @ljcarot !

**Review by JennySanchez — APPROVED** [review]
LGTM. Let me know if you would like me to merge the PR, Linda.

**Pull request merged**
