### PR TITLE
Adding the content model to the leadspace block

### PR DESCRIPTION
**Pull request by mfearer94**
I added the content model to the leadspace block. I utilized the same format as was used for Leadspace. I also added an anchor link at the top for the user to quickly get to this section.

### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

Screen Shot 2021-01-27 at 9 57 52 AM

### Changelog

**New**

- content model
- anchor link

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by JennySanchez** [comment]
@mfearer94 The "Content guidance" section looks good and we need to get @wonilsuhibm's input to make sure the information for the content style/model on his mind is all covered. I wonder if we should turn the "Link list" and "CTA" into text links and link them to their own website page so adopters can learn more about them if they would like to? What do you think?

**Comment by mfearer94** [comment]
@JennySanchez That's perfect! I was thinking about doing that, but didn't know how to add links like that in a table. Fortunately, I just figured it out so I can add those in. Would you rather have us approve this PR and then I can make another one, or I can just close this PR and create a whole new one with all the changes. What would you prefer?

**Comment by wonilsuhibm** [comment]
Thank you, Michael and Jenny. This looks great, simple, straight forward.

Two questions

1. will people know which piece is which piece? Eg) Which part of the design is `TOC Headline Override` etc? Should we include some form of anatomy diagram?

2. should we publish our content size tokens somewhere on our website? Currently it lives on this [Git Wiki](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards). And reference it from the content model table?
3.

**Comment by mfearer94** [comment]
@wonilsuhibm @JennySanchez @jeffchew Here are the updates we discussed. They are available at this link: https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/831/components/lead-space-block#content-guidance
Please let me know if you would like me to make any other changes. Thanks!

**Review by JennySanchez — APPROVED** [review]
@mfearer94 Can you double check the field names on the table vs the link labels? They are incorrect.
For example, Video is linked to the Video Player. CTA is linked to the Button Group.

**Comment by wonilsuhibm** [comment]
Looking great. 

@mfearer94 @JennySanchez We should probably line up the components linked from this page to be the next to receive content models?

**Comment by JennySanchez** [comment]
> We should probably line up the components linked from this page to be the next to receive content models?

Sounds good to me. @mfearer94 ?

**Pull request merged**
