### PR TITLE
fix(ResourceLinks): add optional multicomponent for different heading

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

[#6882](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6882)

### Description

Add `multiComponent` boolean to allow for different heading type and text when `ResourceLinks` are combined on one page

Example of using `multiComponent`

`<ResourceLinks name="Image" type="ui" multiComponent/>
<ResourceLinks name="Image with caption" type="ui" multiComponent/>`

Screen Shot 2021-08-13 at 9 54 08 AM

### Changelog

**New**

- boolean multiComponent

**Changed**

- add additional checks for resourceLinks

### CODE REVIEW

**Review by janchild — COMMENTED** [review]
Thank you, @ariellalgilmore! This looks great to me! 

Just triple-checking that without `multiComponent` the heading would be H2 `Resources`. Is that correct? Thank you!

**Comment by ariellalgilmore** [comment]
> Thank you, @ariellalgilmore! This looks great to me!
> 
> Just triple-checking that without `multiComponent` the heading would be H2 `Resources`. Is that correct? Thank you!

yup! You can see in the deploy preview https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1141/components/back-to-top#resources that nothing has changed because none of the components have the `multiComponent` boolean yet.

**Comment by ariellalgilmore** [comment]
> > Thank you, @ariellalgilmore! This looks great to me!
> > Just triple-checking that without `multiComponent` the heading would be H2 `Resources`. Is that correct? Thank you!
> 
> yup! You can see in the deploy preview https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1141/components/back-to-top#resources that nothing has changed because none of the components have the `multiComponent` prop yet.

**Review by janchild — APPROVED** [review]
🥂 Thank you, @ariellalgilmore !!

**Comment by shixiedesign** [comment]
🤩

**Pull request merged**
