### PR TITLE
docs(tutorial): update badge image and final link to credly

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

Refs https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5157

### Description

This includes the final updates to the `wrapping up` page of the tutorial, which includes the link to the Credly page and the updated badge imagery.

The navigation is also opened up to include the tutorial link.

### Changelog

**Changed**

- Updated `nav-items.yml` to include tutorial
- Added Credly link on `Wrapping Up`
- Updated badge image on `Wrapping Up`

### CODE REVIEW

**Comment by jeffchew** [comment]
We are also waiting to have this PR merged in so badge submission can happen there: https://github.com/carbon-design-system/carbon-badges/pull/9

**Comment by oliviaflory** [comment]
@jeffchew thank you for updating!

I think without the white background it looks a bit big on the page than the previous design and because it's a bit lower resolution it's a little bit fuzzy.

Screen Shot 2022-01-12 at 6 09 01 PM
Screen Shot 2022-01-12 at 6 09 38 PM


Could we try doing 6 or 4 columns rather than the default 8 for the image width? I'm also happy to put it on a white background if you would like.

This is how I've set up a 6 column image:
```
<Row>

<Column colMd={4} colLg={6}>

![A visual example of the Filter panel component](../../images/component/filter-panel/filter-panel-default.jpg)

<Caption>Carbon for IBM.com Developer Essentials Web Components badge</Caption>

</Column>

</Row>

```

**Comment by jeffchew** [comment]
Sorry @oliviaflory , this fell off my radar!

I updated the image to have a white background: 
https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1430/developing/web-components-tutorial/wrapping-up

**Review by oliviaflory — APPROVED** [review]
Thanks @jeffchew looks better!

Do you want to hold off merging this until Matt has everything wrapped up on his end?

**Comment by jeffchew** [comment]
> Thanks @jeffchew looks better!
> 
> Do you want to hold off merging this until Matt has everything wrapped up on his end?

Thanks @oliviaflory !

Yes, let's hold off until the PR https://github.com/carbon-design-system/carbon-badges/pull/9 has been merged by @mattrosno .

**Pull request merged**
