### PR TITLE
Carousel content page

### PR DESCRIPTION
**Pull request by jacobottesen-dgc**
### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by JennySanchez** [comment]
@jacobottesen-dgc  Thank you for getting the Carousel page content together. 

Here are a few findings to share with you for another look.

- For "This components", can we indicate if this is a UI or Layout component?
Screen Shot 2020-11-23 at 10 23 04 AM

- For the images, I wonder if it looks like the image cust off on the right-hand side. What do you both think? Wonil and Olivia?
Screen Shot 2020-11-23 at 10 34 54 AM

- For the text link, we might only make "Card" as a link but not "component".
Screen Shot 2020-11-23 at 10 27 19 AM

**Comment by JennySanchez** [comment]
@wonilsuhibm @oliviaflory The content for the Carousel page is ready for you to take a look.

**Comment by wonilsuhibm** [comment]
@jacobottesen-dgc @JennySanchez thank you.

Re some for the screenshots, should we start using the style that was used on the new masthead page?

- Separating the component itself from the image background
Screen Shot 2020-12-03 at 10 19 57 AM

**Comment by wonilsuhibm** [comment]
Re the introduction and the first section, Carousel, their purposes are repeating and overlapping—let's merge them into one.

---

[Lead space]

### The carousel is as an exploratory component, meaning it allows users to browse or explore multiple pieces of content within the same area of the page. This layout component is commonly used when you have a large amount of similar content needed on a page, but you don’t want to increase the screen real estate. It includes a headline, cards, controls, an optional sub-copy, and an optional CTA text link.  

[Image]

Link 1
Link 2
Link 3

### Anatmoy
...
...

---

Another option is to add the image under the anatomy section.

**Comment by wonilsuhibm** [comment]
Seems that the TOC anchor links are missing anatomy?

**Comment by wonilsuhibm** [comment]
@JennySanchez I tried moving around the content pieces, this makes the most sense to me—the paragraph under **Carousel** has been moved to replace the intro copy. Then the visual was moved to under the **Anatomy** section. 

screencapture-localhost-8000-components-carousel-2020-12-03-10_54_15

**Comment by JennySanchez** [comment]
@wonilsuhibm This breaks the pattern we have for the content structure across the Components section.

I'd recommend having the section tile "Default" added as the first section to keep the consistency across the Components website pages and break the content out as the following:

---

(intro copy)
The carousel is as an exploratory component, meaning it allows users to browse or explore multiple pieces of content within the same area of the page. 

#### Default
This layout component is commonly used when you have a large amount of similar content needed on a page, but you don’t want to increase the screen real estate. It includes a headline, cards, controls, an optional sub-copy, and an optional CTA text link.  

(Image of the Carousel)

#### Anatomy

(Image of the Carousel Anatomy)

**Comment by wonilsuhibm** [comment]
Hmmm, I kind of like this structure, but not sure about the heading, default, especially since we don't have alternate versions.

I feel that this is the right structure:

- Design
- Anatomy
- Usage guidance
- Design and func docs
- Dev docs
- Feedback

And if there are multiple designs, then we can add them under Design:

- Design
   - Default
   - Alt 1
   - Alt 2
- Anatomy
- Usage guidance
- Design and func docs
- Dev docs
- Feedback

**Review by oliviaflory — COMMENTED** [review]
Made a few suggestions to update some language based on our slack conversation

**Review by JennySanchez — APPROVED** [review]
Made all the updates based on the feedback from Wonil and Olivia and we should be good to go.

**Comment by JennySanchez** [comment]
@wonilsuhibm Page nav label, title, and content updated from "Carousel" to "Card section – carousel" as discussed.

**Comment by wonilsuhibm** [comment]
Looks good to me. Thank you @JennySanchez

**Pull request merged**
