### PR TITLE
Add Tabs extended media page

### PR DESCRIPTION
**Pull request by shixiedesign**
### Related Ticket(s)

#892 

### Changelog

**New**

- add Tabs extended media page

### CODE REVIEW

**Comment by JennySanchez** [comment]
@shixiedesign For the components website page, we only show the desktop view as the Default. If you would like to show how other breakpoint views look like, please create a section with the title "Behavior," and you can give more context on how the mobile view should be. You can find an example on the Masthead component page.

As mentioned on Slack, we do not use captions for every image on the website, especially for the Default image on the components pages. Please take the caption off the Default image.

**Comment by shixiedesign** [comment]
> The Tabs extended link in the Default paragraph is not linked correctly.

That link is not gonna work until the `Tabs extended` page is merged. Link address is correct.

**Comment by shixiedesign** [comment]
@JennySanchez ready for another review!

**Comment by JennySanchez** [comment]
@shixiedesign The page looks good. The only thing that needs update will be the Development documentation stats for React. It should have the Under construction label and Coming soon (see screenshot below) if it's not available.
Screen Shot 2021-05-14 at 3 20 33 PM

**Comment by JennySanchez** [comment]
I checked again and still can not see the `Under construction` label shows up via preview.
@shixiedesign @kennylam Can you see it?

Screen Shot 2021-05-17 at 4 52 17 PM

**Review by JennySanchez — APPROVED** [review]
Label fixed and we are good to go.

**Pull request merged**
