### PR TITLE
Adding the new Footer V2 images

### PR DESCRIPTION
**Pull request by DragosRistici**
Updated the footer images with the new image production guidelines implemented. Also small typos corrected.

### CODE REVIEW

**Comment by shixiedesign** [comment]
@DragosRistici oops you got the number indexed backwards from the image annotation! 

image

**Comment by DragosRistici** [comment]
> @DragosRistici oops you got the number indexed backwards from the image annotation!
> 
> image

I need a vacation ahaha. Thank you for spotting it. Done.

**Comment by DragosRistici** [comment]
Updates will be made live when the dev enhancements are ready. Until then, you can [see the page here](https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1070/index.html).

**Review by shixiedesign — APPROVED** [review]
Looks good!

**Pull request merged**
